### PR TITLE
Make vault_token optional

### LINKED ISSUE #17: Don't crash when no VAULT_TOKEN is set
As far as I understand it, the "vault" feature is optional, i.e. as long as you don't call any vault-related functions, everything is fine.

Therefore it would be nice if isopod would not crash `F1220 09:23:31.797004   11785 main.go:59] --vault_token or $VAULT_TOKEN must be set` and instead would ignore it. Currently I'm forced to `export VAULT_TOKEN=none` everywhere, which is of course doable, but a bit annoying.

### PR DESCRIPTION
**Pull request by jonnylangefeld**
* move `vaultToken` and `namespace` to optional flags, since they aren't
  required if vault is not used and since `namespace` has a default
* add sample certs to ingress example to not rely on vault for example
* fix a bug of pr #24 ([click here to jump to line](https://github.com/cruise-automation/isopod/pull/24/files#diff-8458d1eb0cc345fde5af185bc24ca63bR63)), that panicked if `vaultkubeconfig` wasn't set

fix #17

### CODE REVIEW

**Comment by jonnylangefeld** [comment]
sample certs could be simple dummy strings (instead of valid pems). The sample deployment would still work, but the sample deployment would also be nonsense. lmk if I should use dummy strings instead.

**Comment by jonnylangefeld** [comment]
tested examples with minikube and `isopod -kubeconfig ~/.kube/config install examples/main.ipd`

File: main.go [hunk 1]
```diff
@@ -55,9 +53,6 @@ var (
 
 func init() {
 	flag.Parse()
-	if *vaultToken == "" {
```
Comment (cxuu) [inline main.go]: Since this check is removed, perhaps we should still assert vault token not empty in the actual vault module when vault is accessed? I think all four read/write methods in this file https://github.com/cruise-automation/isopod/blob/master/pkg/vault/vault.go#L63 should have some check similar to 
```go
if p.client.Token() == "" {
    return errors.New("Tried to access Vault but token is empty. Please set --vault_token or $VAULT_TOKEN")
} 
```
and maybe extract this to a short function.

File: examples/ingress.ipd [hunk 2]
```diff
@@ -41,7 +41,170 @@ def install(ctx):
         data=[corev1.Namespace(metadata=metav1.ObjectMeta(name=namespace))],
     )
 
-    tls = vault.read("secret/piedpiper.com")
+    tls = {
```
Comment (cxuu) [inline examples/ingress.ipd]: This will allow us to test using the example code, which is great. However, the original purpose of this file was to illustrate how isopod is useful, and hardcoding values as such make the example less readable. I am thinking maybe we could extract this value to another file, say `example/fake-tls.star`, which will look like the following

```python
fake_tls = {
    "ca-bundle": "...",
    "crt": "...",
    "key": "...",
}
```

and in `examples/ingress.ipd`

```python
load("helpers.ipd", "env_from_secret", "container_port", ... )
load("fake-tls.ipd", "fake_tls")

...

# You may read TLS config from Vault, such as:
#
#     tls = vault.read("secret/piedpiper.com")
# 
# Here, we use a fake value to implement a runnable example without access to Vault.
tls = fake_tls

...
```

File: pkg/cloud/onprem/onprem.go [hunk 3]
```diff
@@ -59,23 +59,25 @@ func NewOnPremBuiltin(kubeConfigFile string) *starlark.Builtin {
...
+	if vaultKubeConfig, ok := o.AbstractKubeVendor.AddonSkyCtx(
+		map[string]string{}).Attrs["vaultkubeconfig"]; ok {
+		kubeConfigVaultPath := vaultKubeConfig.(starlark.String).String()
 
-	// Should only access vault kubeconfig if the kubeConfigFile flag was not set
-	// and the vaultkubeconfig attribute is set in the star config.
-	if len(kubeConfigVaultPath) > 0 && len(o.kubeConfigFile) < 1 {
-		// Remove the surrounding quotes from the Starlark string
-		kubeConfigVaultPath = strings.Trim(kubeConfigVaultPath, `"`)
+		// Should only access vault kubeconfig if the kubeConfigFile flag was not set
```
Comment (cxuu) [inline pkg/cloud/onprem/onprem.go]: hmm I just notice that this comment is not ture. If the vaultkubeconfig attribute is set then the onprem() cluster will always use vaultkubeconfig rather than kubeConfigFile flag. I am fine with the existing behavior. Since you are on this, perhaps you could update the comment here to reflect the truth?

Comment (jonnylangefeld) [reply pkg/cloud/onprem/onprem.go]: Hmm maybe I'm missing something, but [line 66](https://github.com/cruise-automation/isopod/pull/27/files#diff-8458d1eb0cc345fde5af185bc24ca63bR68) `if len(kubeConfigVaultPath) > 0 && len(o.kubeConfigFile) < 1 {`  only enters the if clause if both conditions are true. So if `kubeConfigVaultPath` is set, but also `o.kubeConfigFile` would not be empty, we wouldn't enter this if clause, even though `kubeConfigVaultPath` is set.
Hence we would fall back to using the file in this case ([line 82](https://github.com/cruise-automation/isopod/pull/27/files#diff-8458d1eb0cc345fde5af185bc24ca63bR82)):
`return clientcmd.BuildConfigFromFlags("", o.kubeConfigFile)` making the comment correct again.
Let me know if I'm getting this wrong :D

Comment (cxuu) [reply pkg/cloud/onprem/onprem.go]: you are absolutely right
